# Generated by Django 4.2.6 on 2023-10-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_id', models.IntegerField()),
                ('book_id', models.IntegerField()),
                ('review_text', models.TextField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('average_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('no_of_books', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestsToBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_id', models.IntegerField()),
                ('request_date', models.DateField()),
                ('book_id', models.IntegerField()),
                ('status', models.CharField(max_length=60)),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShippedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('book_id', models.IntegerField()),
                ('from_address', models.TextField(max_length=200)),
                ('to_address', models.TextField(max_length=200)),
                ('transaction_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('last_updated', models.DateField()),
                ('is_public', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='question_text',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='J. K. Rowling', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='condition_desc',
            field=models.CharField(default='Good', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='Nice', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='genre_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='ISBN', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.TextField(default='India', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='owner_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='Available', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='Harry Potter', max_length=50),
        ),
    ]
