# Generated by Django 4.2.6 on 2023-11-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='default_cover.jpg', upload_to='images/'),
        ),
    ]
