# Generated by Django 4.2.6 on 2023-11-15 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_book_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
