# Generated by Django 4.2.6 on 2023-11-15 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippedto',
            name='from_address',
        ),
        migrations.RemoveField(
            model_name='shippedto',
            name='to_address',
        ),
        migrations.AddField(
            model_name='shippedto',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shippedto',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
