# Generated by Django 4.2.6 on 2023-11-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_shippedto_from_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
